package expo.modules.trustwalletcore

import org.junit.Assert.assertEquals
import org.junit.Test

// Plain JVM unit test (no wallet-core JNI needed) — verifies Bech32.encodeSegwitV0.
//
// p2wpkhVectorMatches is checked against a real, independently-known-valid mainnet address
// (its checksum was verified by decoding it with a from-scratch bech32 decoder before use
// here — this isn't just a hand-copied hex string). p2wshVectorMatches and
// testnetHrpVectorMatches exercise the same (by then proven-correct) encoder on a 32-byte
// program and a different hrp, generated by that same verified implementation.
class Bech32Test {

  private fun hexToBytes(hex: String): ByteArray =
    ByteArray(hex.length / 2) { ((Character.digit(hex[it * 2], 16) shl 4) + Character.digit(hex[it * 2 + 1], 16)).toByte() }

  @Test
  fun p2wpkhVectorMatches() {
    val program = hexToBytes("751e76e8199196d454941c45d1b3a323f1433bd6")
    assertEquals("bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4", Bech32.encodeSegwitV0("bc", program))
  }

  @Test
  fun p2wshVectorMatches() {
    val program = hexToBytes("1863143c14c5166804bd19203356da136c985678cd4d27a1b8c6329604903262")
    assertEquals("bc1qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3qccfmv3", Bech32.encodeSegwitV0("bc", program))
  }

  @Test
  fun testnetHrpVectorMatches() {
    val program = hexToBytes("1863143c14c5166804bd19203356da136c985678cd4d27a1b8c6329604903262")
    assertEquals("tb1qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3q0sl5k7", Bech32.encodeSegwitV0("tb", program))
  }
}
